version: "3"
services:
    gaia:
        build: .
        image: gaia
        ports:
            - '8080:8080'
        environment:
            - "GAIA_MONGODB_URI=mongodb://mongo/gaia"

    mongo:
        build:
            context: .
            dockerfile: ./Dockerfile-db
        image: gaia-db